### ISSUE TITLE
Supress logging in tests

### ISSUE THREAD

**Issue by gildurao** [SourceHorizon/logger#17]
👋 

I was wondering, is there a way to supress logs when running flutter tests?

**Comment by Bungeefan** [comment]
I am not aware of a specific flag for when running flutter tests, however you could add a custom filter which returns false when running in tests.

**Comment by Bungeefan** [comment]
As this seems to be resolved, I am going to close this issue.
If you need additional assistance or want to provide another solution, feel free to ping me and I will re-open the issue.
