### ISSUE TITLE
Can you support custom rules for discarding stacktrace lines? 

### ISSUE THREAD

**Issue by fingerart** [SourceHorizon/logger#52]

**Comment by Bungeefan** [comment]
Hi, this should already be possible with #13.
Additionally, next time please state your question in the description, not in the issue title, thanks!

**Comment by fingerart** [comment]
Would it be more flexible to use regular expressions?
https://github.com/SourceHorizon/logger/blob/main/lib/src/printers/pretty_printer.dart#L290

**Comment by Bungeefan** [comment]
No problem. For sure, but that could also result in slower logs as the checks can be more expensive, depending on the regex.
