### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by busslina** [SourceHorizon/logger#60]
This case is on web (console) but I think it happens in sever (file).

```dart
log.t('Websocket connection -- On done (Stream) -- $id');
```
Prints in web console this:
```
�[38;5;244m[T]�[0m  Websocket connection -- On done (Stream) -- [NOT SET YET]
```

It is weird because it is printing okay this:
```
[D]  Connecting to Webosckets Server
```

My logger is:
```dart
Logger(
      level: use(appCapsule).logLevel.casted,  // trace
      filter: ProductionFilter(),
      output: ConsoleOutput(),
      printer: SimplePrinter(),
    )
```

**Comment by busslina** [comment]
It is due to `logger` using ANSI color codes when using `ConsoleOutput`, so maybe this lib have to check if it is a web console and not use colored strings

**Comment by Bungeefan** [comment]
Hi, yeah, it seems that the browser consoles do not support the ANSI color codes.
Fortunately, this can be easily solved by adding `colors: false` to the constructor of the respective printer.

Nevertheless, I am not really a fan of making the default behavior platform dependent. If the user doesn't want colors, it is easy to configure in the constructor, heck if it is desired, even the user can make it platform dependent for their project in one single line ;)
```dart
printer: PrettyPrinter(
  colors: !const bool.fromEnvironment('dart.library.js_util'),
),
```

**Comment by busslina** [comment]
@Bungeefan Thank you, O didn't knew that option
