### ISSUE TITLE
DevelopmentFilter should not check against assert, 

### ISSUE THREAD

**Issue by cedvdb** [SourceHorizon/logger#63]
- If I want to disable logs in production I can set the log level to OFF appropriately.
  - This library should not make that decision for me especially since it currently does not work as intended, see https://github.com/SourceHorizon/logger/issues/10

  Proposal: 

Reconsider the design decision of not enabling logs when asserts are disabled: Development filter would allow everything that is above the log level, as one would expect, whether asserts are enabled or not.

**Comment by Bungeefan** [comment]
Hi!
First, I think it's quite sensible to disable logging by default in production, especially if one of the main use cases is an embedded app on a device that has no console output. But I agree, the name `DevelopmentFilter` can be confusing at first.

Second, the library doesn't "make that decision for you", it provides a reasonable but **configurable** default.
You don't have to like it, but you can easily change it to your preference. Just set the `filter` to the provided `ProductionFilter` which behaves exactly the way you want it to.

By the way, it indeed works the way it is "intended", maybe not the way some people expect (understandably), but still as intended.
*Actually, #57 has helped to improve the documentation on this one.*

**Comment by cedvdb** [comment]
> especially if one of the main use cases is an embedded app on a device that has no console output
 
 That's where I disagree: That's opinion based at this point, if the library is designed around flutter and console output so be it, so I'm closing this.
