### ISSUE TITLE
feat: Expose message, error, and stackTrace in OutputEvent 

### ISSUE THREAD

**Issue by cedvdb** [SourceHorizon/logger#64]
Similar to https://github.com/simc/logger/pull/133

To be able to do: 

```
class FirebaseOutput extends LogOutput {
  List<Level> levels;

  FirebaseOutput({
    this.levels = const [Level.error],
  });

  @override
  void output(OutputEvent event) {
    if (levels.contains(event.level)) {
      FirebaseCrashlytics.instance.recordError(
          event.error,
          event.stackTrace,
          reason: event.message);
    }
  }

}

```

**Comment by Bungeefan** [comment]
Hi, as [already linked](https://github.com/simc/logger/pull/133#ref-commit-a6970d9) in your mentioned issue, this has been implemented via a6970d9e847b875b4d0f2f154745e89484418190 a while ago.
You should be able to access the original `LogEvent` simply via the `origin` field in `OutputEvent`.
