### ISSUE TITLE
why FileOutput has many "ECS" letter in files on android? look my picture

### ISSUE THREAD

**Issue by yaochangliang159** [SourceHorizon/logger#75]
![WX20240515-163054@2x](https://github.com/SourceHorizon/logger/assets/13497352/5f9c5b8c-0b10-436f-840e-343b6e85847c)

my logger version logger: ^2.3.0

my flutter doctor

![WX20240515-163147@2x](https://github.com/SourceHorizon/logger/assets/13497352/d5838914-6665-4a65-ad4f-de1ffb9d8641)

**Comment by Bungeefan** [comment]
These are ASCII escape sequences due to a bug in Flutter on iOS.
See #66 for more information.
