### ISSUE TITLE
loggerTheme to be used in ThemeData to globaly set default logger settings

### ISSUE THREAD

**Issue by Priyantha-Kingslake** [SourceHorizon/logger#78]
Can a `loggerTheme` property be implemented in `ThemeData` so that we may set a global state for the logger? 

The default `Logger` is with `PrettyPrinter`, implementing this allows us to change the default into our requirement. Set it to `SimplePrinter` as an example

**Comment by Bungeefan** [comment]
Hi, I am not quite sure if it's a good idea to create a theme-like class for a logger (especially if it's only for one or two printers). I mean a logger isn't a widget, not even close to one IMO.

Maybe you can refine your idea, so I can better understand what you would expect from such a feature.
