### ISSUE TITLE
为什么在Android和iOS上打印的效果不一样呢

### ISSUE THREAD

**Issue by sing1** [SourceHorizon/logger#79]
![image](https://github.com/SourceHorizon/logger/assets/15246585/3a4fc847-2154-4d02-8698-69a5747a98fe)
这是运行在IOS手机上的效果

![image](https://github.com/SourceHorizon/logger/assets/15246585/8a28ffb8-113b-4bec-a74d-a6637e7373be)
这是运行在Android手机上的效果

代码是一模一样的，但是打印出的日志是不一样的

**Comment by Bungeefan** [comment]
Hi, this was already answered in #18.
