### ISSUE TITLE
Log formatting in console

### ISSUE THREAD

**Issue by vlkonoshenko** [SourceHorizon/logger#81]
I have a problem with console log formatting. Maybe I missed some configuration?
Create instance 
`final logger = Logger();`
Use it
`logger.i('AppLifecycleWrapper.checkUserDistance - distance changed');`

First, the screen displays my console and the second screen is an example from pub.dev. 
<img width="1349" alt="Снимок экрана 2024-08-02 в 13 14 14" src="https://github.com/user-attachments/assets/c8b574a3-8b38-4b5f-96d4-f2458507aaa6">
<img width="694" alt="Снимок экрана 2024-08-02 в 13 16 35" src="https://github.com/user-attachments/assets/7e66f31a-6204-41e8-b134-737fb4daf66b">

**Comment by Bungeefan** [comment]
Hi, please have a look at #66.

**Comment by vlkonoshenko** [comment]
@Bungeefan  Thank you!
