### ISSUE TITLE
Unexpected characters in logger output

### ISSUE THREAD

**Issue by ShaneBridges** [SourceHorizon/logger#87]
Good day,
I recently noticed the following issue with weird characters (Unicode I presume) being printed whenever I use the logger package.

Code:
![Screenshot 2024-10-06 222849](https://github.com/user-attachments/assets/d5903649-3201-43df-bccc-11f2ca0b52c5)

Output:
![Screenshot 2024-10-06 221522](https://github.com/user-attachments/assets/06b0427b-8510-4407-8a64-5826c6ff8e22)

I have the version set to "logger: ^2.4.0" in pubspec.yaml and I'm using the latest version of dart/flutter/VS Code/Windows 11.  In case it's helpful, I create the logger as follows:

`static final Logger _logger = Logger(printer: PrettyPrinter(methodCount: 0, errorMethodCount: 0, noBoxingByDefault: true));`

All other VS code output looks normal when debugging...except for whatever I log with logger.  Not sure when it started happening...

Any help/tips would be appreciated - I'm not sure if it's a recent bug or an issue on my end (quote possibly!).

Thanks!

**Comment by ronnygomezp21** [comment]
Hello, it seems that it is a problem with the most recent version because this same problem began to appear on Friday, October 4.
![image](https://github.com/user-attachments/assets/219bd2bb-f097-4b73-9c6d-2391fd1273b3)

**Comment by ronnygomezp21** [comment]
Hi, I have been experiencing the same problem since Friday, October 4th.
![image](https://github.com/user-attachments/assets/6e7ed8ba-43e2-4370-bbc6-ad3dc2e14631)

**Comment by Bungeefan** [comment]
Hi, as this seems to be only happening in VS Code, I suspect that the ANSI colors are not correctly parsed by the Flutter extension, which is not something `logger` can fix.
However, you can work around this visual bug by disabling `colors` in `PrettyPrinter` for the time being:
```dart
var logger = Logger(
  printer: PrettyPrinter(colors: false),
);
```

The issue seems to have already been reported: https://github.com/Dart-Code/Dart-Code/issues/5302
