### ISSUE TITLE
Why haven't all the logs been output

### ISSUE THREAD

**Issue by alexsunday** [SourceHorizon/logger#88]
```dart
import 'package:logger/logger.dart';

void main() async {
  final logger = Logger(
      level: Level.all,
      filter: null,
      output: null,
      printer: SimplePrinter(printTime: true));
  print('hello');
  logger.d("debug?");
  logger.i("hello info");
  logger.w("warn???");
  logger.e("error?");
  print('are you kidding me?');
}
```

![image](https://github.com/user-attachments/assets/0ec50c12-48e8-4d83-8e02-0532c49c8d37)

**Comment by Bungeefan** [comment]
Hi, this has already been answered many times before (e.g. https://github.com/SourceHorizon/logger/issues/43#issuecomment-1706266924).
You either need to provide another `LogFilter` or enable `asserts` to be able to see logs in "release" builds:

> The default implementation (`DevelopmentFilter`) shows all logs with `level >= Logger.level` while in debug mode (i.e., running dart with `--enable-asserts`).
**In release mode all logs are omitted.**

https://github.com/SourceHorizon/logger?tab=readme-ov-file#logfilter
